---
apiVersion: v1
kind: Service
metadata:
  name: automotriz-jj-backend
  namespace: automotriz-jj
  labels:
    app: automotriz-jj
    component: backend
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "false"
spec:
  type: ClusterIP  # ClusterIP para uso interno con Ingress
  selector:
    app: automotriz-jj
    component: backend
  ports:
  - name: http
    protocol: TCP
    port: 8000
    targetPort: 8000
  sessionAffinity: None