---
apiVersion: v1
kind: Service
metadata:
  name: automotriz-jj-frontend
  namespace: automotriz-jj
  labels:
    app: automotriz-jj
    component: frontend
spec:
  type: LoadBalancer  #LoadBalancer, ClusterIP
  selector:
    app: automotriz-jj
    component: frontend
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  sessionAffinity: None